import type { Metadata } from "next";
import { Inter, Space_Mono, Syne } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { Analytics } from "@vercel/analytics/next";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const spaceMono = Space_Mono({ weight: ["400", "700"], subsets: ["latin"], variable: "--font-space-mono" });
const syne = Syne({ weight: ["700", "800"], subsets: ["latin"], variable: "--font-syne" });

export const metadata: Metadata = {
  title: "Mehdi Sahari — Freelance IA & Automatisation | Montpellier",
  description:
    "Consultant en automatisation à Montpellier · Workflows n8n, agents IA et création de SaaS sur mesure. 3 ans d'expérience. Obtenez un audit gratuit →",
  metadataBase: new URL("https://mehdisahari.fr"),
  authors: [{ name: "Mehdi Sahari" }],
  robots: { index: true, follow: true },
  alternates: {
    canonical: "https://mehdisahari.fr",
    languages: {
      fr: "https://mehdisahari.fr/",
      "x-default": "https://mehdisahari.fr/",
    },
  },
  openGraph: {
    type: "website",
    siteName: "Mehdi Sahari",
    title: "Mehdi Sahari — Consultant en Automatisation",
    description:
      "Automatisation n8n, création de SaaS et sites web qui convertissent. Basé à Montpellier, disponible partout en France et en Europe.",
    url: "https://mehdisahari.fr",
    locale: "fr_FR",
    // OG image auto-generated by opengraph-image.tsx (PNG 1200x630)
  },
  twitter: {
    card: "summary_large_image",
    site: "@Mehdi_shri",
    creator: "@Mehdi_shri",
    title: "Mehdi Sahari — Consultant en Automatisation",
    description: "Automatisation n8n, création de SaaS et sites web qui convertissent.",
    // Twitter image auto-generated by opengraph-image.tsx
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr" className={`${inter.variable} ${spaceMono.variable} ${syne.variable}`}>
      <head>
        <meta name="theme-color" content="#2563eb" />
        <link rel="icon" href="/favicon.svg" type="image/svg+xml" />
        <link rel="apple-touch-icon" href="/favicon.svg" />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "ProfessionalService",
              name: "Mehdi Sahari — Automatisation & IA",
              image: "https://mehdisahari.fr/photo.jpeg",
              url: "https://mehdisahari.fr",
              email: "mehdi.shr@outlook.fr",
              telephone: "",
              description:
                "Consultant freelance en automatisation n8n, agents IA et création de SaaS sur mesure à Montpellier. 3 ans d'expérience.",
              address: {
                "@type": "PostalAddress",
                addressLocality: "Montpellier",
                addressRegion: "Occitanie",
                postalCode: "34000",
                addressCountry: "FR",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: 43.6108,
                longitude: 3.8767,
              },
              areaServed: [
                { "@type": "City", name: "Montpellier" },
                { "@type": "Country", name: "France" },
                { "@type": "Country", name: "Belgique" },
                { "@type": "Country", name: "Luxembourg" },
                { "@type": "Country", name: "Suisse" },
              ],
              priceRange: "$$",
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "5",
                reviewCount: "3",
                bestRating: "5",
              },
              review: [
                {
                  "@type": "Review",
                  author: { "@type": "Organization", name: "Engie" },
                  reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
                  reviewBody: "Développement fullstack solide et livraison dans les temps.",
                },
                {
                  "@type": "Review",
                  author: { "@type": "Organization", name: "Crédit Agricole" },
                  reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
                  reviewBody: "Intégration technique fiable et communication transparente.",
                },
                {
                  "@type": "Review",
                  author: { "@type": "Organization", name: "CILcare" },
                  reviewRating: { "@type": "Rating", ratingValue: "5", bestRating: "5" },
                  reviewBody: "Automatisation efficace des process internes avec n8n.",
                },
              ],
              founder: {
                "@type": "Person",
                name: "Mehdi Sahari",
                jobTitle: "Consultant en Automatisation & IA",
                url: "https://mehdisahari.fr",
                image: "https://mehdisahari.fr/photo.jpeg",
                sameAs: ["https://www.linkedin.com/in/mehdi-sahari/"],
                knowsAbout: ["n8n", "React", "Next.js", "NestJS", "SaaS", "Automatisation", "TypeScript", "PostgreSQL", "Supabase", "Intelligence Artificielle"],
              },
              sameAs: ["https://www.linkedin.com/in/mehdi-sahari/"],
            }),
          }}
        />
      </head>
      <body>
        <Providers>{children}</Providers>
        <Analytics />
      </body>
    </html>
  );
}
